#!/usr/bin/env python3
"""Generate the perf-repro fixture set for djouallah/duckrun#16.

Creates deliberately trivial dbt nodes whose only purpose is to exist as Delta tables, so
that read-only commands (`dbt show -s <one model>`) trigger duckrun's project-wide relation
discovery at realistic scale (the slow part happens BEFORE the selected node runs):

  dbt/models/perf/set_a/perf_a_model_NN.sql   one static row each, schema perf_a
  dbt/models/perf/set_b/perf_b_model_NN.sql   one static row each, schema perf_b
  dbt/snapshots/perf/perf_snapshots.yml       check-strategy snapshots over the first
                                              models of each set (schema perf_snap,
                                              silver catalog via the project-wide
                                              `snapshots: +database: silver`)

Everything carries the tag `perf_repro`:

  dbt build -s tag:perf_repro          # materialize once (first run takes a few minutes)
  dbt show -s dim_publicholidays       # then measure discovery against ~70 extra tables
  dbt build --exclude tag:perf_repro   # keep normal runs unaffected

Re-run with different sizes via --models-per-set / --snapshots (the script wipes and
rewrites the generated directories, so shrinking the set never leaves strays behind).
Remove the fixture entirely by deleting dbt/models/perf/, dbt/snapshots/perf/ and the
two `perf:` config blocks in dbt_project.yml.
"""
import argparse
import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MODELS_DIR = REPO_ROOT / "dbt" / "models" / "perf"
SNAPSHOTS_DIR = REPO_ROOT / "dbt" / "snapshots" / "perf"

MODEL_SQL = """\
-- Perf-repro fixture for djouallah/duckrun#16: content is irrelevant, only the existence
-- of the Delta table matters. Generated by tools/generate_perf_repro.py.
select
    1 as id,
    '{name}' as payload,
    cast('2026-01-01' as date) as loaded_on
"""

SNAPSHOT_ENTRY = """\
  - name: {name}
    relation: ref('{model}')
    config:
      schema: perf_snap
      unique_key: id
      strategy: check
      check_cols: [payload]
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--models-per-set", type=int, default=25,
                        help="models per schema (2 schemas: perf_a, perf_b); default 25")
    parser.add_argument("--snapshots", type=int, default=18,
                        help="snapshots, spread over both sets; default 18")
    args = parser.parse_args()
    if args.snapshots > 2 * args.models_per_set:
        parser.error("--snapshots cannot exceed the number of models (2 x --models-per-set)")

    for directory in (MODELS_DIR, SNAPSHOTS_DIR):
        shutil.rmtree(directory, ignore_errors=True)

    models = []
    for set_name in ("a", "b"):
        set_dir = MODELS_DIR / f"set_{set_name}"
        set_dir.mkdir(parents=True)
        for i in range(1, args.models_per_set + 1):
            name = f"perf_{set_name}_model_{i:02d}"
            (set_dir / f"{name}.sql").write_text(MODEL_SQL.format(name=name))
            models.append(name)

    # Alternate sets so both schemas contribute snapshot sources.
    interleaved = [m for pair in zip(models[:args.models_per_set],
                                     models[args.models_per_set:]) for m in pair]
    SNAPSHOTS_DIR.mkdir(parents=True)
    entries = [
        SNAPSHOT_ENTRY.format(name=f"perf_snapshot_{i:02d}", model=model)
        for i, model in enumerate(interleaved[:args.snapshots], start=1)
    ]
    (SNAPSHOTS_DIR / "perf_snapshots.yml").write_text(
        "# Perf-repro fixture for djouallah/duckrun#16 — generated by"
        " tools/generate_perf_repro.py.\n"
        "# Static sources -> the first `dbt build` creates one version per snapshot, later"
        " runs no-op.\n"
        "snapshots:\n" + "".join(entries)
    )

    print(f"generated {2 * args.models_per_set} models (set_a/set_b) and"
          f" {args.snapshots} snapshots under {MODELS_DIR.parent}")


if __name__ == "__main__":
    main()
