-- Perf-repro fixture for djouallah/duckrun#16: content is irrelevant, only the existence
-- of the Delta table matters. Generated by tools/generate_perf_repro.py.
select
    1 as id,
    'perf_a_model_03' as payload,
    cast('2026-01-01' as date) as loaded_on
